sudo: enabled
language: node_js
node_js: v10.13.0

install:
 - npm install

script:
 - echo 'No tests yet'

before_deploy:
 - npm install
 - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    tags: true